name: Test Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        with:
          dry-run: true
          root-path: "./sample-project"

          # For Chrome Extension
          chrome: true
          chrome-extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          chrome-client-id: ${{ secrets.CHROME_CLIENT_ID }}
          chrome-client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          chrome-refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

          # For Firefox Addon
          firefox: false
          firefox-extension-id: ${{ secrets.FIREFOX_EXTENSION_ID }}
          firefox-jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          firefox-jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}

          # For Edge Extension
          edge: true
          edge-product-id: ${{ secrets.EDGE_PRODUCT_ID }}
          edge-client-id: ${{ secrets.EDGE_CLIENT_ID }}
          edge-client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          edge-access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
